# Generated by Django 5.0.6 on 2024-07-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='employee.hobby'),
        ),
    ]
